### PR TITLE
Fix wack inputs requirement

### PR DESCRIPTION
**Pull request by csjh**
### Description

Adds a dummy fetch during SSR to evaluate the page and saturate a map that gets inputs and sql strings from the page

Couldn't get `node-async.js` working so queries are still evaluated synchronously - not a major concern right now, more of a worry when we're doing motherduck querying, and shouldn't be an impossible fix

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by ItsMeBrianD** [comment]
Will this account for nested inputs? (e.g. if I made a filter row component that included dropdowns)

**Comment by csjh** [comment]
Ah forgot nested inputs was a req, shouldn't be too difficult

**Comment by csjh** [comment]
Some very hacky stuff is needed for nesting, we could do with more `Array.isArray` and `instanceof QueryStore` checks around

**Comment by ItsMeBrianD** [comment]
Not a blocker but another thought; will this support nested input components?

e.g. if I have some (reusable) report section that has filters on it, will those filters work;

(this is a component not a page)
```ReportSection.svelte
<Dropdown name="Category" />
<Datepicker name="DayOf" />

<!-- some query -->
<!-- some dataviz -->
```

**Comment by csjh** [comment]
It should work, as long as you're getting the `inputs` store from context properly and everything.

**Pull request merged**
