### PR TITLE
Fix example project

### PR DESCRIPTION
**Pull request by archiewood**
### Description

The example project now runs 

```bash
pnpm run sources:example-project
pnpm run dev:core-components
pnpm run dev:example-project
```

## To Do
- fix templated page syntax

### CODE REVIEW

**Comment by archiewood** [comment]
This is pretty helpful - Lots of stuff is now working!

There are a few charts that are not working and are hanging in the skeleton loading state.

**Comment by ItsMeBrianD** [comment]
Merging in next may fix those hanging charts, depending on when this was branched off

**Comment by archiewood** [comment]
@ItsMeBrianD it does!

**Comment by archiewood** [comment]
tests are failing - but I think that is because tests on next are failing too

**Pull request merged**
