### PR TITLE
Fix grid printing & add landscape print support

### PR DESCRIPTION
**Pull request by hughess**
(Updated)

### Description
- Adds support for landscape printing
- Fixes printing for Grid components, which were previously incorrectly sized and overlapped each other

### Example
Same page shown printed in portrait and landscape

CleanShot 2024-04-03 at 20 21 22@2x
CleanShot 2024-04-03 at 20 21 13@2x

### Introduced in this PR
- Sets a fixed print width for portrait pages at 650px and landscape pages at 841px (assumes 8.5x11 page).
- Sets maximum grid columns at 2 for portrait and 3 for landscape
- Adds context to the Grid component to share with child components - charts are now aware they are inside a Grid, the number of columns in the grid, and the gap width

### Known Issues
- Safari printing is affected by the width of the browser window when print is selected. This does not happen in other browsers
   - Recommendation is to print using another major browser, or adjust your browser window width until the print output meets your needs

### Implementation Notes
- When a chart is in a Grid, the print action creates 2 images for each chart and swaps it out based on the size of the page
   - This relies on hardcoded numbers for gap widths and page widths 

### Checklist
- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by hughess** [comment]
Update: have tested on the following browsers and all looks good

- MacOS
   - Chrome
   - Safari
   - Firefox 
- Windows
   - Chrome
   - Firefox
   - Edge

**Comment by hughess** [comment]
Print width of 100% doesn’t work on iOS Safari, I assume because of the same echartsCopy dimension issue

**Comment by mcrascal** [comment]
This causes the width of the browser when the print event is fired to affect what is actually printed. 


Printing from a medium width: 

CleanShot 2024-03-28 at 09 39 21@2x


Printing from a narrow width: 
CleanShot 2024-03-28 at 09 39 28@2x

**Comment by hughess** [comment]
It looks like there's a timing issue where echarts doesn't get the dimensions of the updated chart container for the printed page size. I'm looking into if there's a way to access that info during the print setup

**Comment by hughess** [comment]
I think I have a solution here, at least until we can figure out something better:

- Generate 2 images of each chart on print - 1 for portrait and 1 for landscape
- Assume portrait maps to anything `sm:` and below per tailwind, and landscape anything above that
- Set `hidden` vs. `block` on the divs containing these images based on the screen width

For charts within a Grid:
- Set up a store within each Grid to track the number of columns and the gap width
- Get the grid context in EChartsCopyTarget and use that to set the correct width for the container based on the screen width settings describe above

**Comment by hughess** [comment]
Just added the grid context approach.

Some things to figure out before it's ready:
- Confirm that page widths are correct for portrait and landscape
- Confirm ideal print behaviour for landscape - at the moment it is constrained by the article
- Tune the grid gap width calcs - something seems off, 2-col grid and 3-col grid are not right-aligned on print at the moment

And for testing:
- Test across browsers
- Test across layout page widths (e.g., with sidebar hidden, etc)

**Review by mcrascal — APPROVED** [review]

**Pull request merged**
