### PR TITLE
Move Show/Hide SQL to own button

### PR DESCRIPTION
**Pull request by archiewood**
### Description

Move back out of menu - users have reported it's hard to find inside the page menu.

CleanShot 2023-04-13 at 22 06 26

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by mcrascal** [comment]
Thanks @archiewood, this is cool, but I'd propose we hold off on this for now.

1. I think it is possible that it is too hard to find the option in the kebab, but I'd rather wait for some more feedback to roll in before reverting. 
2. If we do pull it back out, I think a less abstract "show / hide queries" button or link is probably preferable to having "SQL" badged on every report.

**Comment by archiewood** [comment]
1. Sounds good. Makes sense to me
2. I played around with a couple of things. Like an eye icon, button with text etc.

This felt like a pretty good trade off on:
- compactness
- not too in your face
- obvious what it does

**Comment by archiewood** [comment]
I think it's also possible that the right place for this _in production_ is:
- query level control of show hide.
- buttons on components "show source" that allow end users to show the data behind a specific component

**Comment by mcrascal** [comment]
Makes perfect sense, I think we'll end up revisiting this. My concern with just badging it "SQL" is more for the completely non technical stakeholder. If was sending a report to someone senior or a sales person or whoever, I would not want it to say SQL or PYTHON or SCALA in the top right.

**Pull request closed without merging**
