### PR TITLE
fix echarts options update

### PR DESCRIPTION
**Pull request by smilingthax**
### Description

Closes https://github.com/evidence-dev/evidence/issues/1795

### Checklist

- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by archiewood** [comment]
hey @smilingthax would you be able to "allow maintainer edits" to all your branches so we can merge in latest?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by smilingthax** [comment]
> hey @smilingthax would you be able to "allow maintainer edits" to all your branches so we can merge in latest?
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

"Allow edits by maintainer" is already checked...

**Comment by archiewood** [comment]
my bad, thanks

**Review by csjh — APPROVED** [review]
Thanks v3 😌

**Pull request merged**
