### PR TITLE
Feat: Motherduck Connector

### PR DESCRIPTION
**Pull request by ItsMeBrianD**
### Checklist

- [ ] ~~For UI or styling changes, I have added a screenshot or gif showing before & after~~
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

### CODE REVIEW

**Comment by mcrascal** [comment]
Docs 😉

**Comment by ItsMeBrianD** [comment]
> Docs 😉

Didn't scratch that checkbox out :shipit:

**Comment by archiewood** [comment]
I'm having issues when testing it out. Have asked the MD team on slack

[!] It looks like Motherduck is taking a bit to connect.
    Motherduck connections are only compatible with motherduck >= 0.10.0
    Make sure that you have upgraded your instance to at least 0.10.0

CleanShot 2024-06-07 at 14 32 34@2x

**Comment by archiewood** [comment]
....miscofiguration from my side, needed to upgrade my motherduck account

**Review by archiewood — APPROVED** [review]

**Pull request merged**
