### PR TITLE
Add `ReferencePoint` and `Callout` components

### PR DESCRIPTION
**Pull request by zachstence**
### Description

Adds `ReferencePoint` and `Callout` components with stories and docs

Resolves https://github.com/evidence-dev/evidence/issues/2073

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] I have added to the docs where applicable
- [x] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by zachstence** [comment]
`ReferencePoint`
image

`Callout`
image

**Comment by archiewood** [comment]
lovely!

so the solution if you have a short string and you want it to not have extra space in the callout is to do `width=0`?

**Comment by zachstence** [comment]
> lovely!
> 
> so the solution if you have a short string and you want it to not have extra space in the callout is to do `width=0`?

@archiewood Hmm actually it would be `width=undefined`, which isn't great... Maybe we should default to no width for the Callout too?

**Comment by zachstence** [comment]
@archiewood Or it could be `width=fit`

**Comment by hughess** [comment]
This is really nice!

It looks like there might be an issue with the default yellow color - getting some flickering on hover. In the past, this has been caused by echarts not knowing how to adjust the color for the hover state (can't remember exactly what triggered it, but something to do with the color code):

CleanShot 2024-07-02 at 12 36 45

**Comment by hughess** [comment]
Only other point of feedback I have on the styling is: I think the grey of the label border is too different vs the grey of the text. 

Might be best to line up with the grey we use for the tooltip border, or maybe a shade darker (+ maybe match the same border radius, slightly less than the current callout radius). That way the greys are on the same scale

**Comment by archiewood** [comment]
Overall like. Good design

QA
- Still getting flicker on the yellow point in the docs
   - Weird hover stuff?
  CleanShot 2024-07-02 at 19 35 52

- maybe it's just a browser thing but I'm seeing almost a drop shadow top-left behind the callout (macos, firefox)
CleanShot 2024-07-02 at 19 32 54@2x
 
- Do i need to be able to pass an array to labelposition to fix stuff like this
CleanShot 2024-07-02 at 19 36 29@2x

- Cursor should probably not be pointer as no action on click
CleanShot 2024-07-02 at 19 43 52

**Comment by zachstence** [comment]
@archiewood Thank you for the feedback!

> Weird hover stuff?
> Cursor should probably not be pointer as no action on click

Fixed by making reference points not hoverable (this is in line with reference area/line functionality)

> maybe it's just a browser thing but I'm seeing almost a drop shadow top-left behind the callout (macos, firefox)

It is likely just something with how ECharts is rendering the one pixel border, it may have been on a pixel border on your monitor resulting in it looking a little thicker. I don't think there's anything I can do to control that.

image

> Do i need to be able to pass an array to labelposition to fix stuff like this for just one of my labels?

I don't know... I feel like if you're using data you would have a dynamic number of items and therefore configuring via a prop wouldn't make much sense. Options I see here:
- Have `labelPosition` accept a column from `data` to use for positioning each point
- The user just has to use `width`/`labelPosition`/add line breaks to try to get the label to not overflow in any spot

I wish ECharts had some way to detect/prevent overflow, but I don't think they do

**Comment by archiewood** [comment]
> Fixed by making reference points not hoverable (this is in line with reference area/line functionality)

it still greys out the Callouts and ReferencePoints when you hover over the line, which is different to the ReferenceLine & Area behaviour

CleanShot 2024-07-03 at 11 28 34

**Pull request merged**
