### PR TITLE
fix: add password to envMap

### PR DESCRIPTION
**Pull request by domtra**
### Description

It isn't possible to use environment variables for building / developing with mysql. Besides some confusion around the names of the env variables, the envMap in mysql seems to be missing the password field.

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by archiewood** [comment]
This looks sensible to me. I guess we missed adding this env var during the recent updates to env var names.

Are you able to add a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

**Review by ItsMeBrianD — APPROVED** [review]
Needs `patch` changeset, as Archie noted; but this looks good to me, thanks for adding this!

**Comment by domtra** [comment]
hey, i tried adding a changeset. hope it is ok like this.
cheers!

**Comment by ItsMeBrianD** [comment]
> hey, i tried adding a changeset. hope it is ok like this. cheers!

Changeset looks perfect, I went ahead and kicked off the tests for the PR

**Pull request merged**
