### PR TITLE
Add page settings menu

### PR DESCRIPTION
**Pull request by archiewood**
### Description
- Moves Hamburger menu to top left
- Adds "Kebab" style settings menu to sidebar
  - Moves Show/Hide Queries Button to Kebab Menu
  - Moves Export to PDF Button to Kebab Menu
- Changes Home breadcrumb for Icon
   - Make Home button accessible from settings 
- Makes sidebar 80% width on mobile
- Adds anchor links to settings menu panels

#### Desktop (dev)
image

#### Desktop (prod)

image

#### Mobile (dev)
image

#### Sidebar

image

#### Deploy (dev only)

CleanShot 2023-03-14 at 20 26 12

#### Show / Hide (dev only)

CleanShot 2023-03-14 at 20 28 04

#### PDF 

CleanShot 2023-03-14 at 20 30 33

#### Docs (dev only)
CleanShot 2023-03-14 at 20 34 35

### Checklist
- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by archiewood** [comment]
Notes:
- [ ] Refactor icon css / js into reusable <Icon/> component
- [ ] Show / Hide Query button test would need to change
- [ ] Fix errors in Node 19 mac/windows

**Comment by archiewood** [comment]
## Follow up edits:
- click to open not hover
- Add link to "Project Settings" in menu, which navigates to `/settings`
- adding "Home" text to `/` and `/settings` routes
- adding test, fixing test which this otherwise breaks due to new location of Show / Hide Queries

## Icons
In this PR I have not really "solved" icons, but hopefully made it easy to swap them out once we have a consistent approach
- I was looking at trying to create a centralised `<Icon name="the-icon-name"/>` component, which wraps the svg to make sure it is positioned, sized and coloured as you want. 
  - However, the best approach here seems to be to {@HTML ...} the svg which I think is not super secure, and also possibly has some performance implications
- We should probably to pick a svelte Icon library with a wide range of stuff we like and pick from those. But this is not a decision I want to take unilaterally just for this. Some promising options
   - [unplugin-icons](https://github.com/antfu/unplugin-icons/tree/main/examples/sveltekit) made by one of the vite core maintainers
   - [tabler icons](https://tabler-icons.io/) also is a huge library with first class svelte support, looks good visually

**Review by Winterhart — APPROVED** [review]
Looks great. I don't have any issue with `vendoring` the `icons` even if we go with a library we will still have an `icons` folder for the `icons` not in the library.

It's very nice to get more UI test 🤩 

(can you wait at the end of the week for the merge?)

**Comment by archiewood** [comment]
I can wait until the end of the week to merge, yes!

**Comment by Winterhart** [comment]
Hey 👋🏼 

can you make sure those two icons are `vendor`? They make the `settings` page super slow on `Codespaces`

Screenshot 2023-03-22 at 4 06 20 PM

**Comment by archiewood** [comment]
Yep I'll add em in

**Pull request merged**
