### PR TITLE
Cartesian [x,y] for ReferenceLine, Error Chart heights

### PR DESCRIPTION
**Pull request by archiewood**
### Description

- create sloping lines by specifying `[x,y],[x2,y2]`
CleanShot 2024-06-04 at 20 52 12@2x
- dates and strings supported
  CleanShot 2024-06-04 at 20 52 19@2x
   ```svelte
    <ReferenceLine 
        x='2019-01-01'   y=80000 
        x2='2021-12-01'  y2=120000
        label="Trend"
    />
   ```
  CleanShot 2024-06-04 at 20 52 38@2x
    ```svelte
    <ReferenceLine 
        x=5000 y=0.01 
        x2=10000 y2=0.09 
        label="[x,y] to [x2,y2]"
    />
    ```
- add symbols to end of line, eg arrow
CleanShot 2024-06-04 at 20 52 27@2x
   ```svelte
    <ReferenceLine 
        x='Japan' y=6500
        x2='Germany' y2=5000
        label="-23%"
        labelPosition=aboveCenter
        lineType=solid
        symbol=arrow
    />
   ```

- reduce errorChart height for ReferenceLine and ReferenceArea
CleanShot 2024-06-04 at 20 52 47@2x
- fix bug which causes multiple Reference lines to be created on HMR

### Issues
- [ ] If any of `x,y,x2,y2` are outside the chart, no line will be drawn
- [ ] Not an amazing UX for trendlines - you need to calc the coefficients and plot the start/end yourself
```svelte
     <ReferenceLine
        x=0
        y={reg[0].slope * 0 + reg[0].intercept}
        x2=400000
        y2={reg[0].slope * 400000 + reg[0].intercept}
        label="Linear Regression"
        labelPosition=aboveCenter
    />
```

### Later
- `<LineChart data={my_query} trendLine=true/>`

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by hughess** [comment]
These are nice! Pretty intuitive to set the coordinates.

A couple of questions:
- Why change the height of the error chart? That won't be consistent with other charts on the page
- What's the reasoning for the change in random ID generation?
 
Some potential issues:
- When you set a coordinate value outside the bounds of the chart, the line doesn't appear, but it's not clear why
- Adding the arrow symbol is cool, though I don't like the style of the arrow. I tried changing it to a triangle arrow, but echarts seems to warp the svg path somehow
- I think there's a use case for applying both `x` and `y` when using `data` if you want to pass in columns (see below)

### Columns example
CleanShot 2024-06-05 at 14 57 54@2x

CleanShot 2024-06-05 at 15 00 05@2x

```html
<ScatterPlot
    data={orders_by_state}
    x=sales_usd
    y=num_orders
    xMin=0
    series=state
>
     <ReferenceLine
       data={reg_update}
       x=x1
       x2=x2
       y=y1
       y2=y2
    />
</ScatterPlot>
```

### Columns alternative
For now for the above example, you can still keep from hardcoding anything by referencing data within each prop:

```html
<ScatterPlot
    data={orders_by_state}
    x=sales_usd
    y=num_orders
    xMin=0
    series=state
>
     <ReferenceLine
        x={reg_update[0].x1}
        x2={reg_update[0].x2}
        y={reg_update[0].y1}
        y2={reg_update[0].y2}
    />
</ScatterPlot>
```

**Comment by hughess** [comment]
here's the code i was using to play around with it:

````

```sql reg_update
with
-- Step 2: Calculate the means of sales_usd and num_orders
means AS (
    SELECT 
        AVG(sales_usd) as mean_sales_usd,
        AVG(num_orders) as mean_num_orders
    FROM ${orders_by_state}
),

-- Step 3: Calculate the sums needed for regression slope and intercept
sums AS (
    SELECT 
        SUM((sales_usd - mean_sales_usd) * (num_orders - mean_num_orders)) as sum_xy,
        SUM((sales_usd - mean_sales_usd) * (sales_usd - mean_sales_usd)) as sum_xx
    FROM ${orders_by_state}, means
),

-- Step 4: Calculate the slope and intercept
regression AS (
    SELECT 
        sum_xy / sum_xx as slope,
        mean_num_orders - (sum_xy / sum_xx) * mean_sales_usd as intercept
    FROM sums, means
),

-- Step 5: Find the minimum and maximum sales_usd values
bounds AS (
    SELECT 
        MIN(sales_usd) as min_sales_usd,
        MAX(sales_usd) as max_sales_usd
    FROM ${orders_by_state}
)

-- Step 6: Calculate the start and end points of the regression line
SELECT
    min_sales_usd as x1,
    max_sales_usd as x2,
    slope * min_sales_usd + intercept as y1,
    slope * max_sales_usd + intercept as y2
FROM regression, bounds
```

<ScatterPlot
    data={orders_by_state}
    x=sales_usd
    y=num_orders
    xMin=0
    series=state
>
     <ReferenceLine
        x=0
        y={reg[0].slope * 0 + reg[0].intercept}
        x2=400000
        y2={reg[0].slope * 400000 + reg[0].intercept}
        label="Linear Regression"
        labelPosition=aboveCenter
    />
</ScatterPlot>

<ScatterPlot
    data={orders_by_state}
    x=sales_usd
    y=num_orders
    xMin=0
    series=state
>
     <ReferenceLine
        x={reg_update[0].x1}
        x2={reg_update[0].x2}
        y={reg_update[0].y1}
        y2={reg_update[0].y2}
    />
</ScatterPlot>

<ScatterPlot
    data={orders_by_state}
    x=sales_usd
    y=num_orders
    xMin=0
    series=state
>
     <ReferenceLine
       data={reg_update}
       x=x1
       x2=x2
       y=y1
       y2=y2
    />
</ScatterPlot>
````

**Comment by archiewood** [comment]
> Why change the height of the error chart? That won't be consistent with other charts on the page
I thought that would be desirable. This error message already appears above the chart that the ReferenceLine is meant to be defined it, but the chart itself is unaffected
CleanShot 2024-06-06 at 10 34 19@2x

> What's the reasoning for the change in random ID generation?
This was not working as I expected in `example-project` (left behind old Reference Lines) But seems like it works fine template. I can revert this

**Review by hughess — APPROVED** [review]

**Comment by mcrascal** [comment]
Nice!

Adam


On Fri, Jun 07, 2024 at 2:18 PM, Archie Sarre Wood ***@***.***

**Comment by mcrascal** [comment]
Nice!

**Pull request merged**
