### PR TITLE
WIP: Flowchart Component

### LINKED ISSUE #1397: Create flow charts
## Feature Description

What would you like to see added to Evidence?
Flow charts so we can convey operational information alongside customer data

## Goal of Feature
What would this feature help you accomplish?
Display some organization flows relevant to clients, along with. Specifically it will help us inform our clients where their sample is along its journey. 

## Current Solution / Workarounds
What do you do today to accomplish the goal you described above?
We've used a sankey chart to display this, but have heard a flow chart is much more helpful. 

## Alternatives
Describe any alternative solutions or features you've considered

### PR DESCRIPTION
**Pull request by ItsMeBrianD**
### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

Resolves #1397

### CODE REVIEW

**Comment by ItsMeBrianD** [comment]
Resolves #1397

**Comment by mcrascal** [comment]
@ItsMeBrianD reminder: this needs to go on `legacy`

**Comment by mcrascal** [comment]
Test w/ multiple flow charts on the same page

**Comment by archiewood** [comment]
Just had follow up from the customer on this. What is the status of this PR?

**Comment by archiewood** [comment]
Netlify keeps running out of memory trying to build this

**Review by archiewood — CHANGES_REQUESTED** [review]
Does not currently build in netlify

**Review by archiewood — APPROVED** [review]

**Pull request merged**
