### PR TITLE
feat: Support SQLite as a source

### LINKED ISSUE #108: SQLite Support

### PR DESCRIPTION
**Pull request by edgarrmondragon**
*TODO*:

- Update docs

Closes #108

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
I think the workflows don't have access to the repo secrets

```
packages/postgres test: ✘   (0 / 1)
packages/postgres test: 
packages/postgres test:    FAIL  "query runs"
packages/postgres test:     connect ECONNREFUSED 127.0.0.1:5432
```

**Comment by hughess** [comment]
Looks like you're right. I think it's because the PR is originating from a fork of the repo and secrets are disabled there by default. I'm going to look into this to see if there's an easy way around it.

**Comment by hughess** [comment]
I've run the tests locally and they all passed. We'll figure out the secrets access separately.

I've added some error handling so the SQLite errors get displayed fully in the query viewer on the page. Last piece is adding to the docs, then we're good to release it! 🎉

**Comment by edgarrmondragon** [comment]
@hughess 

> I've added some error handling so the SQLite errors get displayed fully in the query viewer on the page. Last piece is adding to the docs, then we're good to release it! 🎉

Awesome. Thanks for the quick turnaround 😄

**Pull request merged**
