### PR TITLE
Order columns outside of DataTable helper components

### PR DESCRIPTION
**Pull request by csjh**
### Description

Cleans up column ordering code so future changes to `<Column />` and column order logic is easier

Not passing in components to `<DataTable {data} />` now does this

User writes
```svelte
<DataTable {data}>
```

We turn into
```svelte
<DataTable {data}>
   {#each column_in_data as id}
       <Column id={id} />
   {/each}
</DataTable>
```

### Checklist

~~- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~

### CODE REVIEW

**Comment by archiewood** [comment]
> **Not** passing in components to <DataTable {data} /> now explicitly becomes

can you clarify what this statement means?

**Comment by csjh** [comment]
One thing to note here is that this approach isn't friendly if we want to add more user-facing components that are used in the slot of `DataTable` - stuff like ```svelte
<DataTable>
    <SearchBar />
</DataTable>
```
but afaik we don't have plans for anything like that (and conventionally we've done props for those sorts of things)

**Comment by zachstence** [comment]
@csjh Looks like the DataTable Reactive Columns story has an `undefined` column, is that expected?

image

**Comment by csjh** [comment]
Yeah, that’s because of a lack of a `defaultValue` on the button

**Review by zachstence — APPROVED** [review]

**Pull request merged**
