### PR TITLE
Clearing visual regressions

### PR DESCRIPTION
**Pull request by nidhi-kala**
### Description
Addressing #736 

- SQLite and DuckDB extension text alignment

| Before | After|
| ------------- | ------------- |
| image | Screenshot 2023-04-13 at 15 27 57  |

- Bullet Points

| Before | After|
| ------------- | ------------- |
| image | Screenshot 2023-04-13 at 16 42 06 |

- No Bars Below Settings Panels on narrow viewports

| Before | After|
| ------------- | ------------- |
| image | Screenshot 2023-04-13 at 16 46 35 |

-All input field heights
| Before | After|
| ------------- | ------------- |
| image |  Screenshot 2023-04-13 at 16 50 20|

-Settings
| Before | After|
| ------------- | ------------- |
| image | Screenshot 2023-04-13 at 16 53 09  |

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] Changeset

### CODE REVIEW

**Review by ItsMeBrianD — COMMENTED** [review]
Thanks for the pull request @nidhi-kala!

I looked over this and the changes look good to me; when you get a chance can you resolve the merge conflicts? 

I merged a linting & formatting PR this week , so it might be worth trying to rebase back onto `main`, or copying these changes to a new branch based on `main`.

Once those are set, I'll go ahead and kick off the preview build!

**Comment by nidhi-kala** [comment]
@ItsMeBrianD Hi! I resolved the merge conflicts. Let me know if there's anything else that needs to be done. :)

**Comment by archiewood** [comment]
could you run the code though our (shiny new) formatter and commit the result?
`pnpm run format`

**Comment by nidhi-kala** [comment]
> could you run the code though our (shiny new) formatter and commit the result? `pnpm run format`

Ofcourse! just did that.

**Comment by archiewood** [comment]
Hi @nidhi-kala,

Mostly looks great.

- Extension text alignment ✅
- Bullet points ✅
- Bars below settings panels in narrow viewports ✅

A couple of things I noticed:
- **Input field heights** - while the text input fields are fixed - the dropdown options menu fields are still taller (eg the one where you pick the db connection)
- **Settings menu icon** - this is still much smaller than in 15.0.1

**Comment by nidhi-kala** [comment]
@archiewood I fixed the dropdown menu height. Thanks for pointing it out :)

The settings icon were the same dimensions as 15.0.1.
these are the dimensions of the settings icon in my branch:
Screenshot 2023-04-17 at 14 57 34

And these are in 15.0.1:

Screenshot 2023-04-17 at 14 51 37

which looks like:
Screenshot 2023-04-17 at 14 36 17
 

I think 24*24 looks better, let me know if this works:
Screenshot 2023-04-17 at 15 00 41

I will commit the changes shortly!

**Comment by archiewood** [comment]
**Settings menu**

Whilst that span may still be at 22px, the icon is definitely smaller visually than it used to be.

**15.0.1**
image
image



**main**
image

image


I *think* the culprit is the tailwind upgrade, which has overriden the defaults tags using border-box rather than content-box
CleanShot 2023-04-17 at 22 59 03

My suspicion is that we will need to override this for this element

**Comment by ItsMeBrianD** [comment]
I would attempt to style the `svg`, rather than `.settings-icon` using the selector `.settings-icon :global(svg)`, that should let us keep `border-box` and also style the icon to the precisely correct size.

**Comment by ItsMeBrianD** [comment]
I went ahead and applied this fix to unblock us for the day. I believe that is the last issue we have here

image

**Comment by archiewood** [comment]
Thanks @nidhi-kala & @ItsMeBrianD !

**Pull request merged**
