### PR TITLE
Clarify Snowflake account number formats

### LINKED ISSUE #655: Snowflake account number format is not always <account_number>.<region>.<cloud>
**Bug Description**

[Depending on where your snowflake instance is hosted](https://docs.snowflake.com/en/user-guide/admin-account-identifier#non-vps-account-locator-formats-by-cloud-platform-and-region), your account number may need to be entered in one of the following formats:
1. `<account_number>.<region>.<cloud>` eg `xy12345.us-central1.gcp`
3. `<account_number>.<region>` eg `xy12345.ap-southeast-1`
2. `<account_number>` eg `xy12345`

We currently suggest users use format 1:
image

When in fact this is not always correct. In particular for us-west-2 (US West Oregon), format 3 is required

**Error Messages and Screenshots**
If you use the wrong format, you will get a `Network error. Could not reach Snowflake.`

**Workarounds**
Try one of the above formats

**Database:**
- [ ] Postgres
- [ ] BigQuery
- [x] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] CSV
- [ ] Other (please specify)

### PR DESCRIPTION
**Pull request by wasimTQ**
### Description
Resolves #655 
Gives users clear understanding of the format of snowflake account number to be entered.

image

### Checklist
- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by wasimTQ** [comment]
@archiewood Should I add a changeset myself or you'll take care of it?

**Comment by archiewood** [comment]
If you could go ahead and add your own that would be great!

**Comment by wasimTQ** [comment]
@archiewood For your reference, I've shifted the info tag codes into a seperate component and added transition to it.

If you have any suggestions on naming, please let me know

**Comment by archiewood** [comment]
> @archiewood For your reference, I've shifted the info tag codes into a seperate component and added transition to it.
> 
> If you have any suggestions on naming, please let me know

That sounds sensible to me, and names look good.

**Pull request merged**
