### PR TITLE
Add Authentication Token caching to Snowflake connector

### PR DESCRIPTION
**Pull request by GriffGeorge**
### Description

When using Browser Based SSO Snowflake connection, a developer will be redirected to their browser once for every snowflake connection attempt (~10 times for our small project). This is annoying for our dashboard devs.

This PR adds the `clientStoreTemporaryCredential` option, according to [Snowflake Node.js driver docs](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#authentication-token-caching). It is off by default, because it could be a security issue in some contexts.

### Checklist

- [x] ~~For UI or styling changes, I have added a screenshot or gif showing before & after~~
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] ~~I have added to the docs where applicable~~
    - I looked, but didn't see any docs that should be updated. It doesn't seem that connection options are explicitly documented on the docs site.
- [x] ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~
    - AFAICT, the VSCode extension doesn't setup connection options, correct me if I'm wrong.

### CODE REVIEW

**Comment by GriffGeorge** [comment]
Note that I don't have a test harness to actually verify this has the intended effect. Does Evidence have such a harness? Or, can I somehow use my branch to build our existing project in order to validate?

**Comment by archiewood** [comment]
Hey @GriffGeorge,

You should be able to test this yourself, by following the steps in https://github.com/evidence-dev/evidence/pull/2706#event-15045563654

**Comment by GriffGeorge** [comment]
@archiewood Thanks!

> You should be able to test this yourself, by following the steps in [#2706 (comment)](https://github.com/evidence-dev/evidence/pull/2706#event-15045563654)

Sorry, this link takes me to the "approval event" of another PR; I don't see any steps there. Are you referring to https://github.com/evidence-dev/evidence/tree/next/sites/example-project ?

**Comment by archiewood** [comment]
apologies - wrong link- updated!

**Comment by ItsMeBrianD** [comment]
Does this resolve #1894?

**Comment by archiewood** [comment]
@ItsMeBrianD - It might, not sure. Maybe @GriffGeorge can verify once it is merged

**Review by archiewood — APPROVED** [review]

**Comment by GriffGeorge** [comment]
@archiewood I did finally get a chance to try it out today. Unfortunately it doesn't work... while the UI is fine, there's no UX issue, but the option doesn't actually fix the bad behaviour. Took me a sec, but I think the reason is that evidence on a year-old version of the snowflake sdk, 1.9.0. The SSO caching option I'm trying to use was only introduced [in 1.12](https://docs.snowflake.com/en/release-notes/clients-drivers/nodejs-2024#version-1-12-0-august-05-2024).

**Comment by archiewood** [comment]
Aha! well a potential solution could be to upgrade the snowflake connector then

**Comment by GriffGeorge** [comment]
Haha yes, workin on it.

**Pull request merged**
