### PR TITLE
fix: adds bottom margin on LinkButton

### LINKED ISSUE #1125: Bottom margin needed on LinkButton
## Steps To Reproduce

CleanShot 2023-08-23 at 12 37 47@2x
CleanShot 2023-08-23 at 12 38 50@2x

### PR DESCRIPTION
**Pull request by yashhhguptaaa**
### Description

Resolves #1125 

Screenshot 2024-04-27 at 11 16 43 AM

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by archiewood** [comment]
Looks good. Can you add a changeset?

**Comment by yashhhguptaaa** [comment]
> Looks good. Can you add a changeset?

Done [9e8f8b1](https://github.com/evidence-dev/evidence/pull/1947/commits/9e8f8b1a817329a273824c30e8475e63f081e8da)

**Comment by yashhhguptaaa** [comment]
> Looks good. Can you add a changeset?

**Comment by archiewood** [comment]
This should be a patch bump - you can change the file to just say "patch" rather than "major"

(Changesets are how we manage semantic versions)

**Comment by yashhhguptaaa** [comment]
> This should be a patch bump - you can change the file to just say "patch" rather than "major"
> 
> (Changesets are how we manage semantic versions)

Ohh, my bad, missed that. Done

**Comment by yashhhguptaaa** [comment]
> > This should be a patch bump - you can change the file to just say "patch" rather than "major"
> > (Changesets are how we manage semantic versions)
> 
> Ohh, my bad, missed that. Done

@archiewood Can we merge this? I've added the changesets as well.

**Review by mcrascal — APPROVED** [review]

**Pull request merged**
