### PR TITLE
fix: remove comments and trailing `;` in sql query

### LINKED ISSUE #733: Remove `;` from the end of query dependencies, if it is there
**Bug Description**
When chaining queries, if a query ends with a `;`, it is not removed when it is chained. This can lead to syntax errors

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
A "correct" query that ends with a `;` should not break when it is used in chaining.

**Error Messages and Screenshots**
If you received any error messages, please post them here. Screenshots are also helpful.
image

**Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.
On any page; use these queries:

\`\`\`a
SELECT 1 as t;
\`\`\`

\`\`\`b
SELECT t * 5 from ${a};
\`\`\`

**Workarounds**
Remove `;`

**Do you want to contribute a fix for this bug?**
Probably

**Database:**
- [ ] Postgres
- [X] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] CSV
- [ ] Other (please specify)

### LINKED ISSUE #1450: Queries cannot end with `;`
## Steps To Reproduce

In markdown

````
```sql test
SELECT 1;
```
````

## Expected Behavior

Query Runs

## Actual Behaviour

```
Parser Error: syntax error at or near ";" LINE XX: SELECT 1;) AS "__userQuery"
```

## Workarounds

Don't terminate your Queries with `;`

### LINKED ISSUE #1735: Source SQL ending with comment breaks evidence sources
## Steps To Reproduce

1. Simple Project w/ Postgres source
2. Add `test.sql` to `sources/mypg/`:
```
SELECT 1
-- comment
``` 
3. run `evidence sources --debug`

## Expected Behavior

The command does not fail.

## Actual Behaviour

```
  test ✖ Cannot read properties of undefined (reading 'rows')
Error: Cannot read properties of undefined (reading 'rows')
    at runQuery (/evidence/node_modules/@evidence-dev/postgres/index.cjs:197:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $18acbd5e40ec20a6$export$53c7a8f067b9e2ba (file:///evidence/node_modules/@evidence-dev/plugin-connector/dist/index.mjs:1350:38)
    at async $acd86e83767fde42$export$76919addde332833 (file:///evidence/node_modules/@evidence-dev/plugin-connector/dist/index.mjs:1581:22)
    at async file:///evidence/node_modules/@evidence-dev/evidence/cli.js:349:3
```

Also, the node command then "hangs", i.e. never returns to the shell.

## Workarounds

Add `;` on a separate line at the end:
```
SELECT 1
-- comment
;
```

## Additional Information

The failing query is here: https://github.com/evidence-dev/evidence/blob/next/packages/postgres/index.cjs#L160  

The culprit is https://github.com/evidence-dev/evidence/blob/next/packages/db-commons/index.cjs#L186 cleanQuery(), calling `.trim()` on the query, which is wrong, because it no longer ends the sql-comment-line.

The hanging command is probably caused by the exception handlers not closing the pg connection(?).

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
### Description

closes #733
closes #1735
closes #1450

Changes:
- Remove single / multiline comments in query.
- Remove trailing `;` in query.
- Completes TODO of `QueryStore` and fixes bug in chained query due to trailing `;`.

Before:
image

After:
image

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by csjh** [comment]
Thanks for the PR!

One concern: seems like queries with string-enclosed "comments" are also caught here, which could be an issue if it's used as a delimiter or such in a string input (i.e. `New York -- NY`)

**Comment by AyushAgrawal-A2** [comment]
@csjh 
Sorry, I missed that edge case. Tackling this requires parsing the query, I don't think it can be done via simple regex replace. I have added a helper function to do so.

This is required in 3 packages. In order to avoid cross package dependencies I have added this in all three packages. But I don't believe duplicate code is good. Please suggest if there is a common place to place this function. I tried placing it in db-commons but it create a cyclic dependency betweet QueryStore and db-commons.

Before:
Screenshot from 2024-04-18 18-47-39
After:
Screenshot from 2024-04-18 18-43-39

**Comment by ItsMeBrianD** [comment]
> This is required in 3 packages. In order to avoid cross package dependencies I have added this in all three packages. But I don't believe duplicate code is good. Please suggest if there is a common place to place this function. I tried placing it in db-commons but it create a cyclic dependency betweet QueryStore and db-commons.

This should only be used in the `query-store` (which is now `sdk/usql/query.js`), and that should cover the impacted area

**Comment by AyushAgrawal-A2** [comment]
> > This is required in 3 packages. In order to avoid cross package dependencies I have added this in all three packages. But I don't believe duplicate code is good. Please suggest if there is a common place to place this function. I tried placing it in db-commons but it create a cyclic dependency betweet QueryStore and db-commons.
> 
> This should only be used in the `query-store` (which is now `sdk/usql/query.js`), and that should cover the impacted area

@ItsMeBrianD 
This is necessary for `preprocess/src/extract-queries/extract-queries.cjs` also so that the dependent queries are cleaned properly.

**Comment by AyushAgrawal-A2** [comment]
> > This is required in 3 packages. In order to avoid cross package dependencies I have added this in all three packages. But I don't believe duplicate code is good. Please suggest if there is a common place to place this function. I tried placing it in db-commons but it create a cyclic dependency betweet QueryStore and db-commons.
> 
> This should only be used in the `query-store` (which is now `sdk/usql/query.js`), and that should cover the impacted area

@ItsMeBrianD 
Done
image

**Review by ItsMeBrianD — APPROVED** [review]

**Comment by ItsMeBrianD** [comment]
This is ready to be merged, but going to hold off until after the release so there is a testing window on `next`, thanks for the contribution!

**Comment by ItsMeBrianD** [comment]
This is addressed in #2103

**Pull request closed without merging**
