### PR TITLE
Add fuzzy searching via fuse.js

### PR DESCRIPTION
**Pull request by csjh**
### Description

Replaces string filtering (with `contains`) with fuzzy searching to enable similarity search filtering in DataTables

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by mcrascal** [comment]
Seems like a huge improvement. 

I think turning down the default [threshold](https://www.fusejs.io/api/options.html#fuzzy-matching-options) might make sense for our case -- I am finding it a little too "loose".  

Maybe would make more sense as a separate issue, but would it be possible to preserve the original height of the table during search and pagination? It's pretty jarring to have the layout shift on keystrokes. 

Other than that LGTM.

**Comment by csjh** [comment]
re: layout shift, do you just mean the shift when it goes from a full page of results -> less than a full page?

**Comment by mcrascal** [comment]
> re: layout shift, do you just mean the shift when it goes from a full page of results -> less than a full page?

Yes exactly. I think ideally the table container would stay the same height. It's a different issue though, we can tackle it separately.  

New threshold seems great to me -- ship it.

**Review by ItsMeBrianD — APPROVED** [review]
This lgtm

**Pull request merged**
