### PR TITLE
Support for AAD authentication in MSSQL connector

### PR DESCRIPTION
**Pull request by mycaule**
### Description

I needed to use this block to be able to login with Active Directory. This is useful if the database uses a passwordless strategy.

```
authentication: {
    type: "azure-active-directory-default"
  }
```

Check also https://github.com/timothyhoward/evidence-connector-mssql/pull/1

### Screenshots

<details>

Screenshot 2024-05-01 at 14 08 17
Screenshot 2024-05-01 at 14 08 30

</details>

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] I have added to the docs where applicable

### CODE REVIEW

**Comment by archiewood** [comment]
@mycaule Thanks for this PR

I feel like `SQL login` is probably not the right name for the username/pw auth flow?

perhaps `Username / Password` is more descriptive

**Comment by mycaule** [comment]
> @mycaule Thanks for this PR
> 
> I feel like `SQL login` is probably not the right name for the username/pw auth flow?
> 
> perhaps `Username / Password` is more descriptive?

I used this because it is the vocabulary used by Microsoft, SQL authentication refer to user/pass created in SQL Server
As opposed to the username/password in Active Directory of your organization.

You can check this screenshot

https://learn.microsoft.com/en-us/azure-data-studio/connect#new-installation-of-azure-data-studio-140-and-higher

**Comment by mycaule** [comment]
Also added the authentication types @timothyhoward supported in his plugin.

**Comment by zachstence** [comment]
Not sure what's going on with the checks here, something related to the Netlify preview URL. @ItsMeBrianD @archiewood any ideas?

**Comment by zachstence** [comment]
@ItsMeBrianD Please review

**Comment by mycaule** [comment]
LGTM

**Review by ItsMeBrianD — APPROVED** [review]

**Comment by ItsMeBrianD** [comment]
@archiewood / @hughess is this good to go from a product perspective?

**Comment by hughess** [comment]
@ItsMeBrianD as long as this works, it's good to go

**Comment by archiewood** [comment]
QA done on this

**Review by archiewood — APPROVED** [review]

**Comment by archiewood** [comment]
Mega thank you @mycaule - and thanks for your patience while we reviewed

**Pull request merged**
