### PR TITLE
Add weighted mean aggregation to DataTable

### PR DESCRIPTION
**Pull request by hughess**
### Description
Adds `weightedMean` as a total aggregation in DataTable/Column. Should be used with `weightCol` to specify the column to pull the weight values from for the calculation. If no `weightCol` supplied, a weight of 1 is used for all values, resulting in the same output as the `mean` aggregation.

datatable-totalrow-agg-functions

```html
<DataTable data={countries} totalRow=true rows=5>
  <Column id=country/>
  <Column id=gdp_usd totalAgg=sum/>
  <Column id=gdp_growth totalAgg=weightedMean weightCol=gdp_usd fmt='pct2'/>
  <Column id=population totalAgg=mean fmt='#,##0"M"'/>
</DataTable>
```

### Checklist
- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] I have added to the docs where applicable

### CODE REVIEW

**Comment by ItsMeBrianD** [comment]
Not sure why all of the changesets are showing as deleted with this branch, this might need to have `origin/next` merged in

**Review by archiewood — APPROVED** [review]

**Comment by archiewood** [comment]
Can this be merged

**Comment by hughess** [comment]
Just attempting to get rid of the deleted changesets then will be good to go

**Comment by hughess** [comment]
@ItsMeBrianD i think this might be caused by main not being merged back into next?

**Comment by hughess** [comment]
I'm at a loss for how to remove the deleted changesets - I've merged with next and synced, but those changes don't seem to be taking effect

**Comment by archiewood** [comment]
solved?

**Comment by hughess** [comment]
That did most of it! Now I’m just not sure why Cormick’s changes are showing up here - they were already merged to next

**Pull request merged**
