### PR TITLE
Fix BigValue format error

### PR DESCRIPTION
**Pull request by csjh**
### Description

Only runs `getFormatObjectFromString` if `fmt` is a string

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by hughess** [comment]
@csjh what was the error? Wondering if this will need to be changed in other places format props are accepted as well (e.g., `xFmt`, `yFmt` in charts)

**Comment by csjh** [comment]
There's a reproduction in #1018, the issue was just that all the reactive portions of `Value.svelte` are in the one block, so whenever `data` updates the entire block reruns, which causes `fmt` (which is a prop that's originally a string but is reassigned in the block) to update again with `fmt = getFormatObjectFromString(fmt, columnSummary[0].format.valueType)`, which messes up the assumption of `fmt` being a string in `getFormatObjectFromString`. Hopefully when we shift everything to JSDoc we'll catch things like this much easier

**Comment by csjh** [comment]
It might need to be changed if we reassign `fmt` anywhere else in that same kind of pattern without type checks

**Comment by hughess** [comment]
Ahh ok. I believe these are the only other places that happens:
- Chart
- SankeyChart
- USMap
- FunnelChart

Is an alternative to use a separate variable rather than overwriting the initial variable?

**Comment by csjh** [comment]
Yeah, separate variable is possible, I just wasn't sure if it was a specific choice meant so there was an option to in format objects or not. If that isn't intended then switching to a different variable is best

**Comment by hughess** [comment]
The intention in this case was only to check if they've supplied a `fmt` argument, but the assumption was that it would always be a string

**Review by hughess — APPROVED** [review]

**Pull request merged**
