### PR TITLE
Layout rev3

### LINKED ISSUE #501: Add organized CSS color vars
**Feature Description**
Colour variables are currently just the colour and a number (e.g. --yellow-400). This makes it hard to quickly implement new themes. Currently, all components seem to reference raw colour variables directly.

**Goal of Feature**
Adding a hierarchy for CSS colour variables is an important part of a design system. This allows for more readable/maintainable code and can be used to allow users to set their own (custom) themes.

**Proposed Solution**
We should organize the colour variables hierarchically, such as:
1. Raw (hexcodes, RGB)
2. Semantic (primary, secondary, etc)
3. Component (text-color, button-background, etc)

This way, we limit the usage of raw colour values, and instead, use semantic-based and component-based colour names. Consideration should be made to the naming schemes for these semantic-based and component-based tokens.

**Examples/Screenshots**
```CSS
:root {
    /* Raw */
    --white: #fff;
    
    /* Theme (Semantic) */
    --primary: var(--white);
    
    /* Component */
    --font-color: var(--primary)
}
```

**Are you interested in contributing this feature?**
Sure, I can contribute to this.

### LINKED ISSUE #573: Missing old style figures in text
**Bug Description**
Numbers in article text should be rendered proportional old style, but currently are not. 

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm (barely) able to keep using Evidence as normal, but flagging this for the team to fix

### LINKED ISSUE #712: DataTable font size inconsistencies in iOS webkit
**Bug Description**
Font sizes look wrong in on iPhone, they are inconsistent between columns

image

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
All table fonts the same size

**Error Messages and Screenshots**
image

Seems like some css is leaking in from CodeBlock?

**Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.
1. Open this website on iPhone (responsive design mode on mac safari does not replicate) https://hilarious-hamster-5fc657.netlify.app/

**Environment Information**
Operating System (iOS):
Package versions: evidence v15

### LINKED ISSUE #739: Migrate default layout and settings page to tailwind
Bring spacing, sizing, colors into accordance with tailwind's spacing system

Clean up regressions: 

- [x] Sticky header should be full width in mobile #749 
- [x] Kebab (three dot) menu: shadows toned down, click outside to dismiss, constrained to article width on wide screen, remove "get help on slack" in production builds #749 
- [x] Settings #736 

Related: 
- #533 
- #610

### LINKED ISSUE #777: Visual regression in Query spacing
**Bug Description**
The query viewers now have too much space between them

Before:
image

After:
image

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

### PR DESCRIPTION
**Pull request by mcrascal**
This is ready for feedback:  

### Goals

1. Modernize the overall layout and make the project feel more cohesive
2. Make it easier to keep things isolated by targetting user markdown with the .markdown class, instead of global styles 
5. Give us a good starting point for tackling some more visual improvements as smaller PRs

### Not goals
1. Restyle every component. I've tried to make minimal changes to existing components just to keep things working. Where I did, this was usually a tailwind conversion inside existing classes. 
3. Fix every existing visual issue or bug. That said, this closes a few.

Closes #573, closes #712, closes #739, closes #777, closes #501

### Notable changes 
1. Default font -> Inter
2. Sidebar, header, table of contents 
4. Adds https://svelte-headlessui.goss.io/docs/2.0/dialog to make an accessible drop down menu, which I wouldn't mind using in a few other places. 
5. Type: headers, and some other type details 
7. Table of contents excludes the page title when set through frontmatter @archiewood  
8. Colours: back to tailwind defaults. Despite spending a fair amount of time obsessing over `gray-200`, our existing palette was quite close to tailwind's defaults anyways.  

### Feedback 
For feedback, it'd be helpful to get it broken into two categories: 

1. Major issues: things that should prevent us from shipping this. 
9. Follow ons: small nits and things you don't like, but that we can tackle in smaller chunks. 

### Next Steps 
- [ ] @csjh can you help me move the fonts out of example project to be packaged _with_ the tailwind package? 
- [ ] @csjh can you take a look at making the tailwind palette import-able into component utilities. We have a colors file that I'd like to link back to the tailwind config. I don't view this as blocking. 
- [x] prevent scrolling the main body when the mobile sidebar is open.

### CODE REVIEW

**Comment by archiewood** [comment]
Dig the skeleton a lot

**Comment by ItsMeBrianD** [comment]
>  @csjh can you take a look at making the tailwind palette import-able into component utilities. We have a colors file that I'd like to link back to the tailwind config. I don't view this as blocking.

the `colors` const is exported from the tailwind configuration package; so we might just need to update the colors to be hex instead of hsla, and that should be enough.

**Comment by csjh** [comment]
> the `colors` const is exported from the tailwind configuration package; so we might just need to update the colors to be hex instead of hsla, and that should be enough.

Does tailwind not recognize HSLA? Or am I misunderstanding

**Comment by csjh** [comment]
> @csjh can you help me move the fonts out of example project to be packaged with the tailwind package?

As in, put the `.woff` files in the tailwind package and use them as static files from there?

**Comment by mcrascal** [comment]
@csjh 

Re colors -- I want [this block](https://github.com/evidence-dev/evidence/blob/3c335bc19ce8f553dccd4c330db1c706e39040ca/packages/component-utilities/src/colours.js#L1) to depend on the colours from whatever tailwind theme is present in the project (similar to how the css vars are created in `app.css`). Just trying to remove hardcodes, and centralize this type of base config in tailwind. 

Re fonts -- I am not sure if that's the best approach, but I have a hunch they should not live in the template's static directory. I'd like them to be accessible to core-components, (or anything else that's using our tailwind preset), and I'd like us to be able to manage them in one place.

**Comment by ItsMeBrianD** [comment]
> Does tailwind not recognize HSLA? Or am I misunderstanding

It does, but the values have an `<alpha-value>` in them which would break when trying to use them in JavaScript, hex wouldn't have this issue

**Review by archiewood — COMMENTED** [review]
## Overall 
- This is a great upgrade. Fixes a lot of UX pain that we've been papering over for a while
- The only thing I feel is that it lacks a bit of character. It's very black and white. Perhaps that is okay as it feels like a blank canvas. I think our current Evidence branding perhaps lacks an accent colour we are happy to use more


## Dig
- Old style numbers
- Sidebar which is unpacked
- Wider
- "On this page"
- Distinction between H1 and H2 in the ToC
- evidence wordmark

## Bugs
- If I open on mobile, I can "scroll" the navbar which feels weird
- I managed to get caught in a scroll issue on mobile - it was scrolling the page behind rather than the sidebar - recording to follow

## Nits
- The error boundaries are inconsistent between Value and Charts 
CleanShot 2023-08-04 at 11 35 19@2x
- error boundary alignment seems off
CleanShot 2023-08-04 at 11 42 47@2x
- maybe we should make it clearer when breadcrumbs are vs are not clickable?
eg you cannot click on Accordion here, but the mouse still turns into a pointer on hover

CleanShot 2023-08-04 at 11 53 18
- `<label>` needs some bottom margin

CleanShot 2023-08-04 at 12 06 48@2x



Not sure:
- Less prominent home icon - I feel like people found it harder to go home before this


## Opportunities
- I think there's now an opportunity to bring the ToC to mobile - you have an "on this page" just at the top of the page , which has a dropdown to show the section headers.

**Comment by mcrascal** [comment]
> If I open on mobile, I can "scroll" the navbar which feels weird

I am not totally sure what the screen cap is showing there. I can't get the header container to actually scroll, but I think you're looking at the overscroll behaviour, which was a bit weird in chrome. I've updated to give the header the same overscroll behaviour as what we have now.  

> I managed to get caught in a scroll issue on mobile - it was scrolling the page behind rather than the sidebar

Resolved, we're now scroll locking the body when the mobile/tablet sidebar is open. 

> The error boundaries are inconsistent between Value and Charts

Toned down the border on the value errors 

> error boundary alignment seems off, remove top margin / padding? 

Only the fonts have been changed. See existing: 

CleanShot 2023-08-07 at 10 17 55@2x

Same with the label. See existing: 

CleanShot 2023-08-07 at 10 18 54@2x

> maybe we should make it clearer when breadcrumbs are vs are not clickable?
eg you cannot click on Ui components here, but the mouse still turns into a pointer on hover

Done. Clickable gets an underline on hover, pointer cursor. Un-clickable gets neither.

**Comment by mcrascal** [comment]
Closing in favour of #1086

**Pull request closed without merging**
