### PR TITLE
Add Heatmap to legacy

### PR DESCRIPTION
**Pull request by hughess**
### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by ItsMeBrianD** [comment]
Should this be pointing to legacy branch instead of `next`?

**Comment by archiewood** [comment]
@ItsMeBrianD presumably this needs a changeset too?
Or do we want to manually version legacy changes?

**Comment by archiewood** [comment]
Dev workspace is going to fail because USQL adds build:sources step which does not exist in legacy

**Comment by ItsMeBrianD** [comment]
> Or do we want to manually version legacy changes?

We can try changesets but we might want to fall back to manual versioning to ensure we don't conflict

**Pull request closed without merging**
