### PR TITLE
Input components 

### PR DESCRIPTION
**Pull request by mcrascal**
Breaks input components out of 1569

### CODE REVIEW

**Review by ItsMeBrianD — APPROVED** [review]

**Comment by csjh** [comment]
I'm just noticing/remembering I never concluded the [dropdown backwards compatibility fix](https://github.com/evidence-dev/evidence/pull/1477#discussion_r1481621082)

I'm leaning on the side of an `includeLabels` prop since it seems cleaner for everyone involved

**Comment by archiewood** [comment]
how would that work?

**Comment by csjh** [comment]
yup

**Comment by archiewood** [comment]
Sounds like a good solution to me.

What do you think about warning a breaking change in the future?


> `${inputs.my_input}` will be deprecated in later versions of evidence. 
>
> Use `${inputs.my_input.value}` in combination with `includeLabels=true`

**Comment by csjh** [comment]
Yeah makes sense to me

**Comment by mcrascal** [comment]
@archiewood I'm inclined to just make the breaking change and announce it in the changelog

**Comment by archiewood** [comment]
That's fine. We should definitely add a major bump in that case

**Pull request merged**
