### PR TITLE
Fix map loading screen layout shift

### PR DESCRIPTION
**Pull request by csjh**
#### Before
before-map

#### After
after-map

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by hughess** [comment]
Nice! is there no margin on the maps when there is no title? Looking at the last map in the "after" gif - looks like it's right up against the previous map. Can't remember if our charts do top / bottom / both for margin

**Comment by csjh** [comment]
@zachstence #2302 was the one I was wondering about, seems like the logic is the same between all the maps except `AreaMap`, which has this extra bit:
image

I don't *think* this is needed anymore?

**Comment by csjh** [comment]
> Nice! is there no margin on the maps when there is no title? Looking at the last map in the "after" gif - looks like it's right up against the previous map. Can't remember if our charts do top / bottom / both for margin

Yeah seems like there's no margin by default

**Comment by hughess** [comment]
While you're in the maps files, can you set up margin so it does the same thing as `<Chart/>`?

**Comment by hughess** [comment]
Here’s an example where the top of the map overlaps content above: https://next-docs-6up4eq5mh-evidence.vercel.app/components/area-map/#custom-tooltip

**Pull request merged**
