### PR TITLE
Semi-fix SQLConsole bug

### PR DESCRIPTION
**Pull request by csjh**
### Description

Fixes `SQLConsole` crashing page on navigation, but only fixes the symptom of some greater bug that has something to do with on-page queries + transitions?

To reproduce the bigger bug:
1. Clone & run https://github.com/csjh/sqlconsole-transition-repro
2. Click on link to test
3. Click on link back to home
4. Witness error in dev console

Suspect it might be a Svelte bug, since I can't figure out anything we would be doing that would make Svelte complain

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Review by ItsMeBrianD — APPROVED** [review]
This looks okay to me, how was this causing an error?

**Comment by archiewood** [comment]
What is the status of this PR? Can it be merged?

**Comment by csjh** [comment]
@ItsMeBrianD a weird svelte bug I'm trying to repo

@archiewood I'll merge as a temp fix, can revert later when there's a full fix on our or svelte side

**Comment by csjh** [comment]
nvm it's fixed in svelte 5

**Pull request merged**
