### PR TITLE
Fix CodeBlock visual regression (Windows. OS)

### PR DESCRIPTION
**Pull request by Winterhart**
### Description

- Fix code block visual regression (Windows OS)

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by archiewood** [comment]
@Winterhart The version I have removes the scrollbar.

image


But it also has weird behaviour on wide tables in the queryviewer: https://evidence-development-workspace-1imcpl7j5-evidence-dev.vercel.app/tables/new-table/

try scrolling all the way to the right of the columns:

image

**Comment by hughess** [comment]
@archiewood I'm taking a look at the scrollbar issues here: https://github.com/evidence-dev/evidence/issues/787
Will continue the discussion there

**Comment by archiewood** [comment]
@Winterhart This is pretty minor and happy if you want to leave it, but I think we should probably remove the margin from the top and bottom of the codeblocks:

image

Removing `margin-top` and `margin-bottom`

CleanShot 2023-04-21 at 15 49 47

**Comment by Winterhart** [comment]
I've added the margin to prevent this:
Screenshot 2023-04-21 at 3 56 26 PM

**Comment by hughess** [comment]
Nice, looking good. Just two things I noticed:

The copy-paste icon moves when the code block is scrolled
CleanShot 2023-04-21 at 15 53 59

On Windows, the scrollbar shows up as the large Windows default one. I've got some code to replace this with a replica of the Mac version - I'll commit that in from my Windows laptop if that works for you!

**Comment by hughess** [comment]
Here's the scrollbar switch I made:

### Before
code-old-scrollbar

### After
code-new-scrollbar

**Comment by Winterhart** [comment]
@hughess I the button is now following the scroll

**Comment by hughess** [comment]
Just made one last change to match up with your changes - it's looking great!

**Review by hughess — APPROVED** [review]

**Pull request merged**
