### PR TITLE
updated camelcase function, updated default value prop

### PR DESCRIPTION
**Pull request by kwongz**
### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by kwongz** [comment]
Updated docs

image

image

**Comment by kwongz** [comment]
Demo of storybook

https://www.loom.com/share/02e88721ff844c7f9e5d1468ebc51149

**Didnt show this drop down working in the video**
image

**Review by archiewood — APPROVED** [review]
LGTM

**Comment by kwongz** [comment]
resolves #1984

**Pull request merged**
