### PR TITLE
Bump duckdb-wasm and arrow

### PR DESCRIPTION
**Pull request by csjh**
### Description

Fixes `devd` compatibility for static build output hosting

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Comment by csjh** [comment]
tests failing due to duckdb/duckdb-wasm#1477

**Comment by archiewood** [comment]
Should we update the test then to a more reasonable number?

**Comment by csjh** [comment]
Sounds fine to me, unless @ItsMeBrianD has an objection

**Comment by ItsMeBrianD** [comment]
Yeah that seems okay

**Review by ItsMeBrianD — APPROVED** [review]

**Pull request merged**
