### PR TITLE
seriesFmt for series labels in charts

### PR DESCRIPTION
**Pull request by kwongz**
### Description

Adding existing evidence/excel formatting properties to series name displayed in chart legends

- [x] Area Chart
- [x] Bar Chart
- [x] Bubble Chart
- [x] Chart
- ~~[ ] Funnel Chart~~ _does not use charts_
- ~~[ ] Histogram~~ _does not accept multiseries_
- [x] Line Chart
- [x] Scatter Plot

_Before:_
`<BarChart {data} />`

image

_After:_

`<BarChart {data} seriesFmt="pct"/>`

image

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by kwongz** [comment]
@archiewood I noticed the styling in the tooltip looked a bit off when using numbers as series names, I took the series name font size down a pixel to help differentiate. What do you think? Open to other ways to highlight series name vs value (underline/bold, different color shade/intensity.

_seriesName & value font 12px_

image

_seriesName font 11px, value font 12px_

image

side note: I also thought (visually) the space between the % values was larger, but there doesn't seem to be the same

**Comment by archiewood** [comment]
were we going to do `seriesLabelFmt` for this?

**Comment by kwongz** [comment]
@archiewood Ready for review

**Comment by archiewood** [comment]
Needs docs!

**Pull request merged**
