### PR TITLE
Clean up stories to fully enable chromatic (2/2)

### PR DESCRIPTION
**Pull request by zachstence**
### Description

Continuation of the work here https://github.com/evidence-dev/evidence/pull/2317

### CODE REVIEW

**Comment by zachstence** [comment]
Was able to see the problem with `CalendarHeatmap` locally. Two runs of `pnpm sources` in `core-components` 3 minutes apart (3:58pm -> 4:01pm) results in _very slightly_ different `departure_date` timestamps, with everything else the same

image

**Comment by archiewood** [comment]
Awesome, so should we turn chromatic on as a required test?

**Comment by zachstence** [comment]
> Awesome, so should we turn chromatic on as a required test?

Not quite yet, still need to clean up the differences that are happening

**Comment by zachstence** [comment]
Just fixed a painful mistake with the faker yaml options (should fix issue with dates not generating the same every time) and batch accepted all changes.

**Comment by zachstence** [comment]
Seems that the label background for references isn't sized correctly sometimes. Not sure why

image

**Review by ItsMeBrianD — APPROVED** [review]

**Pull request merged**
