### PR TITLE
Docs: Add First dashboard tutorial (PR 3)

### PR DESCRIPTION
**Pull request by sometimescasey**
(reopened from https://github.com/evidence-dev/evidence/pull/2047 bc I merged from main instead of next and messed up the revert)

### Description

A "first 10 minutes in Evidence" tutorial.

Taking inspiration from https://guides.rubyonrails.org/getting_started.html.

Feel free to Slack me comments or leave feedback directly on the PR!

image

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] (I assume N/A) I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] I have added to the docs where applicable
- [ ] (I assume N/A) I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

### CODE REVIEW

**Comment by sometimescasey** [comment]
```Set your project token as the CHROMATIC_PROJECT_TOKEN environment variable```

Feel free to either disregard this failure or share the token w me, either works :)

**Comment by archiewood** [comment]
we can ignore these chromatic tests for this

**Comment by ItsMeBrianD** [comment]
@archiewood what's the status on this?

**Comment by sometimescasey** [comment]
> @archiewood what's the status on this?

Hey @ItsMeBrianD! Still WIP on some edits - apologies for the delay, I was away last week as well.

I'm going to redo the images so the highlight colors are consistent shape/colors, and I think that's the only big change remaining.

@archiewood let me know if there's anything else from your feedback doc that I haven't already addressed which is a blocker

**Comment by archiewood** [comment]
@sometimescasey the only other thing I noticed - seems like the header numbering needs to be reset?

CleanShot 2024-07-16 at 10 41 19@2x

**Comment by sometimescasey** [comment]
Hey @archiewood - apologies again for the massive delay, but I found some time this weekend:

- Images updated for consistent color / shape of highlighting
- Removed unused images
- Section numbering updated
- Edited some of the explanation sections on sources and markdown queries based on your feedback
- Went over the doc for tone; took the most colloquial sounding bits and made them a bit more formal, but I thought re-writing the whole thing in passive voice would be overkill. Let me know your thoughts

It looks like you guys have moved to Vercel for deploys and I'm not authorized to your org, but I verified that this succeeds locally:

```
export NODE_OPTIONS="--max-old-space-size=4096"
pnpm build:docs
pnpm run preview:docs
```

Let me know your feedback and next steps!

**Comment by archiewood** [comment]
@sometimescasey thank you for this!

This is ready to go.

I've made a few edits:
- Integrated styling and components to use Evidence components where possible
- A bit of terminology we have recently updated: Project/Dashboard -> App
- There was one query name which was being reused which is not allowed, so I appended `_top100`

**Review by archiewood — APPROVED** [review]

**Comment by sometimescasey** [comment]
Amazing!! Thanks for getting it to the finish line. And gratitude to everyone for the patience around this as well - I know it took a long time. 🙏🏻 Curious re whether folks will find it helpful!

**Comment by mcrascal** [comment]
@sometimescasey this is a fantastic contribution, thank you! I expect this will become one of the most popular pages across all of our web properties. Thousand of people are going to read this and be helped by this.

**Comment by sometimescasey** [comment]
@mcrascal thanks so much, comment made my day :) Hope that is true! Let me know how it lands with users

**Pull request merged**
