### PR TITLE
feat: add on:click to ECharts

### PR DESCRIPTION
**Pull request by jjagielka**
### Description

Adds `on:click` event handler to `ECharts` component.

Now you can:
```svelte
<script>
    function click_handler(ev) {
        const params = ev.detail;
        console.log(params);
    }
</script>

<ECharts config={
    {
        tooltip: {
            formatter: '{b}: {c} ({d}%)'
        },
        series: [
        {
          type: 'pie',
          data: pie_data,
        }
      ]
      }
    }
    on:click={click_handler}
/>
```
or add `link` to your custom chart ex. `PieChart.svelte`:

```svelte
<script>
    import ECharts from "@evidence-dev/components/viz/ECharts.svelte";

    export let data;
    export let link = undefined;

    function handleClick(url) {
        if (link) {
		window.location = url;
	}
    }
</script>

<ECharts
    config={{
        tooltip: {
            formatter: "{b}: {c} ({d}%)",
        },
        series: [ { type: "pie",  data },
        ],
    }}
    {data}
    on:click={({detail}) => handleClick(detail.data[link])}
/>
```
### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### CODE REVIEW

**Review by ItsMeBrianD — APPROVED** [review]
This looks good to me, thanks for including the example code!

If you can add a changeset, then we can get this merged; you can run `pnpm changeset` to bring up the CLI, then commit the generated file once done.

**Comment by jjagielka** [comment]
I have changed `echarts.js` and `ECharts.svelte` in the `example-project` folder. However after more scanning I have found that there are 3 copies of those files in folders:
- ./sites/example-project/src/components/modules/echarts.js
- ./packages/components/modules/echarts.js
- ./packages/evidence/template/src/components/modules/echarts.js

Which location is the one to change? All three of them?

**Comment by ItsMeBrianD** [comment]
> ./packages/components/modules/echarts.js
./packages/evidence/template/src/components/modules/echarts.js

These can be ignored, they should just be auto-generated copies of what you created.

`changeset` here is referring to a tool we use to help manage releases, there is some more information in the [Contribution Guidelines](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset).

If you run the `pnpm changeset` command in the root of the repository, it will prompt you to indicate if changes are `patch`/`minor`/`major` (in this case I believe they are `patch`), and then ask for a short description of the changes. Once that prompt is complete, there will be a new markdown file in the `./.changeset` directory that you can commit to the branch.

**Comment by archiewood** [comment]
This looks good to me.

Really excited about this, as it would allow us to extend this in the future to make it possible to easily configure charts to accept URLs on click:

````svelte

```sql orders_by_category
select
   date_trunc('month', order_datetime) as month,
   category,
   '/category/' || category as category_link,
   sum(sales) as sales_usd
from orders
group by 1,2,3
```


<BarChart 
   data={orders_by_category} 
   x=month
   y=sales_usd
   series=category
   seriesLink=category_link
/>
````

**Pull request merged**
