### PR TITLE
minimal venn diagram implementation

### PR DESCRIPTION
**Pull request by mcrascal**
### Description
This implements a simple Venn Diagram per a customer request. 

This is sufficient for their use case, but it is not ready for prime-time. Propose we leave this undocumented, and open an issue for a broader diagrams suite in the future. 

* Does not offer robust data handling. Overlap percentages, labels, and amounts are supplied directly through props which accept arrays. Live data would be supplied using `query[row].column` syntax. 
* No automatic calculation of overlap percentages. There are a variety of approaches to calculating these, and we're not enforcing any one. For example, sets expressed as a percentage of a total records, sets expressed as a percentage of a single category of records etc.  
* No format handling -- default percentages for overlaps, en-gb for record counts. 

## Syntax 

```
<VennDiagram
    labels={["Title A", "Title B", "Title C"]}
    amounts={["AMOUNT A", "AMOUNT B", "AMOUNT C"]}
    overlaps={["A", "AB", "BC", "AC", "ABC"]}
/>
```

## Screenshot 

CleanShot 2023-01-26 at 21 14 57@2x

### CODE REVIEW

**Comment by mcrascal** [comment]
CleanShot 2023-01-26 at 21 13 30@2x

**Comment by archiewood** [comment]
Visually this looks really good.

I'm a little puzzled on the labelling. Two items:

1. I'm assuming the customer would want to label the absolute values for all of the sets, not just the A-- -B- and --C values?

2. Given the terminology, it's slightly unclear what the numbers next to the labels represent: is the number next to First Malaysian a count of all values associated with first Malaysian? (A--, AB-, A-C, ABC) Or it is the values that are _only_ first Malaysian (ie A--)

**Review by archiewood — COMMENTED** [review]
Aside from comments re labels, everything looks excellent

**Comment by mcrascal** [comment]
> I'm assuming the customer would want to label the absolute values for all of the sets, not just the A-- -B- and --C values?

They don't have a case for that -- their set overlaps are calculated as a percentage of A, but for completeness that would make sense.  

> Given the props terminology, it's slightly unclear what the numbers next to the labels represent 

These accept arbitrary values. Users could slot in anything, or nothing, in each of the labels. In the customer's case they represent total records for each category (A--, B--, C--). 

I'm going to ship this and open a second issue for documenting the feature, and providing a friendlier interface. We can prioritize that when appropriate.

**Pull request merged**
