### PR TITLE
removed scroll to top and fixed esc close for fullscreen mode

### PR DESCRIPTION
**Pull request by kwongz**
### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- ~~I have added to the docs where applicable~~
- ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

1. Removed Scroll to top
2. Removed Scroll when modal is open
3. Fixed esc key behaviour that locked user out from fullscreen mode

https://www.loom.com/share/127253117d0840f3af0650cae7ff0699

### CODE REVIEW

**Review by mcrascal — APPROVED** [review]

**Comment by kwongz** [comment]
vertical scroll removed
before:
image

after:
image

focus appears on dialog modal open in firefox as well
image

**Comment by kwongz** [comment]
fix #2144

**Comment by mdp1125** [comment]
hey @kwongz thanks for pushing these changes. However, I noticed that now when clicking fullscreen on result sets where the full screen should have multiple pages to click through, the < [page number] > section is cut off. Was that intentional? It is a really necessary use case for our users, they click open fullscreen and then will page through the results in the fullscreen mode

**Comment by mdp1125** [comment]
> hey @kwongz thanks for pushing these changes. However, I noticed that now when clicking fullscreen on result sets where the full screen should have multiple pages to click through, the < [page number] > section is cut off. Was that intentional? It is a really necessary use case for our users, they click open fullscreen and then will page through the results in the fullscreen mode

See new issue here: https://github.com/evidence-dev/evidence/issues/2447

**Pull request merged**
